baseURL = "https://tim-beatham.com"
languageCode = "en-gb"
title = "Tim Beatham"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Tim Beatham"

    [languages.en.params]
      subtitle = "Tim Beatham's blogging site"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"

    [languages.en.params.logo]
      logoText = "Tim Beatham"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

[caches]
  [caches.images]
    dir = ":cacheDir/images"
